import { createSlice, createAsyncThunk, createEntityAdapter } from '@reduxjs/toolkit'
import { fetchPlatforms } from '../../api/mockApi'

// createEntityAdapter gives us a normalized shape automatically:
// { ids: [...], entities: { id: {...} } }
const platformsAdapter = createEntityAdapter()

export const loadPlatforms = createAsyncThunk(
  'platforms/loadPlatforms',
  async () => {
    const data = await fetchPlatforms()
    return data
  }
)

const platformsSlice = createSlice({
  name: 'platforms',
  initialState: platformsAdapter.getInitialState({
    status: 'idle', // idle | loading | succeeded | failed
    error: null,
  }),
  reducers: {},
  extraReducers: (builder) => {
    builder
      .addCase(loadPlatforms.pending, (state) => {
        state.status = 'loading'
        state.error = null
      })
      .addCase(loadPlatforms.fulfilled, (state, action) => {
        state.status = 'succeeded'
        platformsAdapter.setAll(state, action.payload)
      })
      .addCase(loadPlatforms.rejected, (state, action) => {
        state.status = 'failed'
        state.error = action.error.message
      })
  },
})

export default platformsSlice.reducer

// Selectors generated by the adapter (normalized access)
export const {
  selectAll: selectAllPlatforms,
  selectById: selectPlatformById,
  selectIds: selectPlatformIds,
} = platformsAdapter.getSelectors((state) => state.platforms)
